// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	UserName     string `json:"user_name" db:"user_name"`
	UserMail     string `json:"user_mail" db:"user_mail"`
	UserPassword string `json:"user_password" db:"user_password"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateUserInput struct {
	UserName        string  `json:"user_name" db:"user_name"`
	UserMail        string  `json:"user_mail" db:"user_mail"`
	UserPassword    string  `json:"user_password" db:"user_password"`
	NewUserName     *string `json:"new_user_name,omitempty" db:"new_user_name"`
	NewUserPassword *string `json:"new_user_password,omitempty" db:"new_user_password"`
}

type User struct {
	ID           string `json:"id" db:"id"`
	UserName     string `json:"user_name" db:"user_name"`
	UserMail     string `json:"user_mail" db:"user_mail"`
	UserPassword string `json:"user_password" db:"user_password"`
}

type UserFilter struct {
	ID           *string `json:"id,omitempty" db:"id"`
	UserName     *string `json:"user_name,omitempty" db:"user_name"`
	UserMail     *string `json:"user_mail,omitempty" db:"user_mail"`
	UserPassword *string `json:"user_password,omitempty" db:"user_password"`
}
