from mcp_init import mcp
import json


@mcp.tool()
def get_skill_categories() -> str:
    """
    Returns standardized skill categories for verification and edge case handling.

    USE THIS TOOL ONLY WHEN:
    - Uncertain if a mentioned skill exists in the standardized system
    - Need to verify skill spelling/format before database operations
    - Handling user input with non-standard skill terminology that needs translation
    - Encountering skill-related errors or validation failures
    - Need to understand skill hierarchy for edge cases (e.g., can "general_labor" substitute for specialized skills in emergencies)
    - Debugging why vector search returned unexpected results

    DO NOT USE FOR:
    - Primary worker-to-task matching (use vector search instead)
    - Regular database queries with existing standardized data
    - General information about project requirements or schedules

    PRIMARY USE CASE: Verification and standardization of ambiguous skill references

    EXAMPLE SCENARIOS:
    - User says "electrician" → Verify/translate to specific electrical subskills
    - Database error with skill format → Check correct terminology
    - Unusual skill mentioned → Confirm if it exists in system
    - Edge case substitution decisions → Understand skill relationships

    Categories include:
    - common_specializations
    - trade_categories
    - primary_skills
    - work_preferences
    - equipment_mastery
    - project_experience
    - certifications
    - safety_training
    """

    skill_categories = {
        "common_specializations": [
            "electrician",
            "plumber",
            "mason",
            "painter",
            "roofer",
            "carpenter",
            "hvac_technician",
            "welder",
        ],
        "trade_categories": [
            "electrical",
            "plumbing",
            "hvac",
            "carpentry",
            "concrete",
            "painting",
            "flooring",
            "welding",
            "roofing",
            "drywall",
            "masonry",
            "heavy_machinery",
            "glazing",
            "insulation",
            "demolition",
            "tiling",
            "logistics",
            "safety",
            "management",
            "general",
        ],
        "primary_skills": [
            {
                "skill": "structural_foundation",
                "subskills": [
                    "concrete_pouring",
                    "concrete_finishing",
                    "rebar_installation",
                    "formwork_construction",
                    "foundation_excavation",
                    "structural_steel_erection",
                    "welding_structural",
                    "pile_driving",
                    "masonry_brick",
                    "masonry_stone",
                    "masonry_block",
                ],
            },
            {
                "skill": "electrical",
                "subskills": [
                    "electrical_installation",
                    "electrical_maintenance",
                    "industrial_wiring",
                    "residential_wiring",
                    "commercial_wiring",
                    "control_panel_wiring",
                    "motor_installation",
                    "lighting_installation",
                    "security_system_installation",
                    "fire_alarm_installation",
                    "data_cable_installation",
                    "fiber_optic_installation",
                    "solar_panel_installation",
                    "electrical_troubleshooting",
                ],
            },
            {
                "skill": "plumbing",
                "subskills": [
                    "plumbing_installation",
                    "plumbing_repair",
                    "pipe_welding",
                    "pipe_fitting",
                    "drain_installation",
                    "water_heater_installation",
                    "bathroom_plumbing",
                    "kitchen_plumbing",
                    "hvac_installation",
                    "ductwork_installation",
                    "ventilation_systems",
                    "air_conditioning_installation",
                    "heating_system_installation",
                    "refrigeration_systems",
                ],
            },
            {
                "skill": "carpentry",
                "subskills": [
                    "framing_wood",
                    "framing_steel",
                    "finish_carpentry",
                    "cabinet_installation",
                    "door_installation",
                    "window_installation",
                    "trim_installation",
                    "deck_construction",
                    "stair_construction",
                    "custom_millwork",
                    "furniture_building",
                    "shelving_installation",
                ],
            },
            {
                "skill": "roofing",
                "subskills": [
                    "shingle_installation",
                    "metal_roofing",
                    "flat_roof_installation",
                    "tile_roofing",
                    "slate_roofing",
                    "roof_repair",
                    "gutter_installation",
                    "skylight_installation",
                    "waterproofing_membrane",
                    "roof_insulation",
                    "chimney_repair",
                    "flashing_installation",
                ],
            },
            {
                "skill": "flooring_tiling",
                "subskills": [
                    "hardwood_flooring",
                    "laminate_installation",
                    "vinyl_flooring",
                    "carpet_installation",
                    "tile_installation_ceramic",
                    "tile_installation_porcelain",
                    "stone_flooring",
                    "marble_installation",
                    "granite_installation",
                    "epoxy_flooring",
                    "polished_concrete",
                    "subfloor_preparation",
                    "floor_leveling",
                ],
            },
            {
                "skill": "painting_finishing",
                "subskills": [
                    "interior_painting",
                    "exterior_painting",
                    "spray_painting",
                    "decorative_painting",
                    "wallpaper_installation",
                    "texture_application",
                    "staining_wood",
                    "epoxy_coating",
                    "line_striping",
                    "graffiti_removal",
                    "surface_preparation",
                    "pressure_washing",
                ],
            },
            {
                "skill": "heavy_machinery_equipment",
                "subskills": [
                    "crane_operation_tower",
                    "crane_operation_mobile",
                    "excavator_operation",
                    "bulldozer_operation",
                    "loader_operation",
                    "forklift_operation",
                    "backhoe_operation",
                    "grader_operation",
                    "compactor_operation",
                    "concrete_pump_operation",
                    "scissor_lift_operation",
                    "boom_lift_operation",
                ],
            },
            {
                "skill": "welding_metal_work",
                "subskills": [
                    "mig_welding",
                    "tig_welding",
                    "stick_welding",
                    "flux_core_welding",
                    "plasma_cutting",
                    "oxy_acetylene_cutting",
                    "structural_welding",
                    "pipe_welding",
                    "underwater_welding",
                    "aluminum_welding",
                    "stainless_steel_welding",
                    "metal_fabrication",
                    "sheet_metal_work",
                ],
            },
            {
                "skill": "insulation_drywall",
                "subskills": [
                    "drywall_installation",
                    "drywall_finishing",
                    "drywall_repair",
                    "blown_insulation",
                    "batt_insulation",
                    "spray_foam_insulation",
                    "rigid_insulation",
                    "vapor_barrier_installation",
                    "acoustic_insulation",
                    "fire_resistant_insulation",
                ],
            },
            {
                "skill": "glass_glazing",
                "subskills": [
                    "window_glazing",
                    "storefront_installation",
                    "curtain_wall_installation",
                    "mirror_installation",
                    "glass_cutting",
                    "auto_glass_installation",
                    "tempered_glass_installation",
                    "laminated_glass_installation",
                ],
            },
            {
                "skill": "demolition_site_work",
                "subskills": [
                    "controlled_demolition",
                    "selective_demolition",
                    "interior_demolition",
                    "concrete_demolition",
                    "asbestos_removal",
                    "lead_abatement",
                    "hazmat_removal",
                    "site_cleanup",
                    "debris_removal",
                    "salvage_operations",
                ],
            },
            {
                "skill": "landscaping_exterior",
                "subskills": [
                    "excavation_grading",
                    "landscaping_installation",
                    "hardscaping",
                    "irrigation_installation",
                    "fence_installation",
                    "retaining_wall_construction",
                    "paving_asphalt",
                    "paving_concrete",
                    "sidewalk_construction",
                    "parking_lot_construction",
                ],
            },
            {
                "skill": "safety_inspection",
                "subskills": [
                    "safety_coordination",
                    "safety_inspection",
                    "quality_control_inspection",
                    "building_inspection",
                    "electrical_inspection",
                    "plumbing_inspection",
                    "structural_inspection",
                    "environmental_monitoring",
                    "fire_safety_inspection",
                ],
            },
            {
                "skill": "general_labor",
                "subskills": [
                    "general_labor",
                    "material_handling",
                    "tool_assistance",
                    "site_cleanup",
                    "equipment_maintenance",
                    "inventory_management",
                    "delivery_coordination",
                    "scaffolding_erection",
                    "temporary_structures",
                ],
            },
        ],
        "work_preferences": [
            {
                "skill": "work_environment",
                "subskills": [
                    "indoor",
                    "outdoor",
                    "height_work",
                    "confined_spaces",
                    "underground_work",
                    "rooftop_work",
                    "basement_work",
                    "attic_work",
                    "crawl_spaces",
                    "climate_controlled",
                    "weather_dependent",
                ],
            },
            {
                "skill": "work_style",
                "subskills": [
                    "teamwork",
                    "solo_work",
                    "leadership_role",
                    "apprentice_mentoring",
                    "client_interaction",
                    "precision_work",
                    "detail_oriented",
                    "problem_solving",
                    "learning_focused",
                    "training_others",
                ],
            },
            {
                "skill": "work_pace_method",
                "subskills": [
                    "fast_paced",
                    "methodical_work",
                    "repetitive_tasks",
                    "varied_tasks",
                    "quality_focused",
                    "speed_focused",
                    "efficiency_oriented",
                    "safety_priority",
                ],
            },
            {
                "skill": "schedule_flexibility",
                "subskills": [
                    "early_hours",
                    "night_shift",
                    "weekend_work",
                    "seasonal_work",
                    "overtime_available",
                    "emergency_response",
                    "on_call_availability",
                    "flexible_schedule",
                    "consistent_hours",
                ],
            },
            {
                "skill": "physical_requirements",
                "subskills": [
                    "physical_work",
                    "heavy_lifting",
                    "light_duty",
                    "kneeling_work",
                    "standing_work",
                    "dust_tolerance",
                    "noise_tolerance",
                    "chemical_exposure_ok",
                    "clean_environment",
                ],
            },
            {
                "skill": "project_commitment",
                "subskills": [
                    "project_based",
                    "long_term_assignments",
                    "driving_required",
                    "local_work_only",
                    "travel_willing",
                ],
            },
            {
                "skill": "work_approach",
                "subskills": [
                    "technical_work",
                    "equipment_operation",
                    "hand_tools_only",
                    "technology_integration",
                    "traditional_methods",
                ],
            },
        ],
        "equipment_mastery": [
            {
                "skill": "hand_tools",
                "subskills": [
                    "hammer",
                    "screwdrivers",
                    "wrenches",
                    "pliers",
                    "chisels",
                    "hand_saws",
                    "levels",
                    "measuring_tape",
                    "squares",
                    "utility_knife",
                    "tin_snips",
                    "pipe_wrench",
                    "adjustable_wrench",
                    "socket_set",
                    "allen_keys",
                    "files",
                    "sandpaper_tools",
                ],
            },
            {
                "skill": "power_tools",
                "subskills": [
                    "drill",
                    "impact_driver",
                    "circular_saw",
                    "reciprocating_saw",
                    "jigsaw",
                    "miter_saw",
                    "table_saw",
                    "angle_grinder",
                    "orbital_sander",
                    "belt_sander",
                    "router",
                    "nail_gun",
                    "staple_gun",
                    "heat_gun",
                    "demolition_hammer",
                    "rotary_hammer",
                    "concrete_mixer",
                    "pressure_washer",
                ],
            },
            {
                "skill": "heavy_machinery",
                "subskills": [
                    "excavator",
                    "bulldozer",
                    "backhoe",
                    "skid_steer",
                    "mini_excavator",
                    "wheel_loader",
                    "dump_truck",
                    "cement_truck",
                    "crane_mobile",
                    "crane_tower",
                    "forklift",
                    "telehandler",
                    "boom_lift",
                    "scissor_lift",
                    "cherry_picker",
                    "man_lift",
                    "compactor",
                    "roller",
                    "grader",
                    "trencher",
                ],
            },
            {
                "skill": "welding_equipment",
                "subskills": [
                    "mig_welder",
                    "tig_welder",
                    "stick_welder",
                    "plasma_cutter",
                    "oxy_acetylene_torch",
                    "cutting_torch",
                    "welding_helmet",
                    "welding_clamps",
                    "angle_grinder_welding",
                ],
            },
            {
                "skill": "electrical_tools",
                "subskills": [
                    "multimeter",
                    "oscilloscope",
                    "wire_strippers",
                    "conduit_bender",
                    "fish_tape",
                    "cable_puller",
                    "voltage_tester",
                    "circuit_tracer",
                    "megohmmeter",
                    "power_quality_analyzer",
                ],
            },
            {
                "skill": "plumbing_tools",
                "subskills": [
                    "pipe_threader",
                    "pipe_cutter",
                    "drain_snake",
                    "hydro_jetter",
                    "leak_detector",
                    "pressure_tester",
                    "soldering_iron",
                    "pipe_wrench_large",
                    "basin_wrench",
                    "closet_auger",
                ],
            },
            {
                "skill": "hvac_equipment",
                "subskills": [
                    "refrigerant_manifold",
                    "vacuum_pump",
                    "leak_detector_hvac",
                    "recovery_machine",
                    "ductwork_tools",
                    "sheet_metal_brake",
                    "crimper",
                    "tube_cutter",
                    "flaring_tool",
                    "refrigerant_scale",
                ],
            },
            {
                "skill": "concrete_tools",
                "subskills": [
                    "concrete_vibrator",
                    "power_screed",
                    "bull_float",
                    "concrete_saw",
                    "rebar_cutter",
                    "rebar_bender",
                    "concrete_pump",
                    "trowels",
                    "floats",
                    "edgers",
                ],
            },
            {
                "skill": "roofing_tools",
                "subskills": [
                    "roofing_nailer",
                    "roofing_hatchet",
                    "chalk_line",
                    "roofing_knife",
                    "membrane_welder",
                    "torch_roofing",
                    "ladder_hooks",
                    "roof_jacks",
                ],
            },
            {
                "skill": "safety_equipment",
                "subskills": [
                    "safety_harness",
                    "hard_hat",
                    "safety_glasses",
                    "respirator",
                    "fall_protection",
                    "confined_space_equipment",
                    "gas_monitor",
                    "emergency_equipment",
                    "first_aid_kit",
                ],
            },
            {
                "skill": "measuring_layout",
                "subskills": [
                    "laser_level",
                    "transit",
                    "total_station",
                    "gps_equipment",
                    "moisture_meter",
                    "infrared_thermometer",
                    "manometer",
                    "sound_meter",
                ],
            },
            {
                "skill": "material_handling",
                "subskills": [
                    "pallet_jack",
                    "hand_truck",
                    "wheelbarrow",
                    "come_along",
                    "chain_hoist",
                    "rigging_equipment",
                    "straps_chains",
                    "dollies",
                ],
            },
            {
                "skill": "technology_equipment",
                "subskills": [
                    "tablet",
                    "smartphone_construction",
                    "laser_scanner",
                    "drone",
                    "bim_software",
                    "cad_software",
                    "project_management_software",
                    "radio_communication",
                    "gps_tracking",
                ],
            },
        ],
        "project_experience": [
            {
                "skill": "residential_projects",
                "subskills": [
                    "residential_single_family",
                    "residential_multi_family",
                    "apartments",
                    "condominiums",
                    "townhouses",
                    "small_residential",
                    "large_residential",
                ],
            },
            {
                "skill": "commercial_projects",
                "subskills": [
                    "commercial_office",
                    "retail_stores",
                    "shopping_centers",
                    "restaurants",
                    "hotels",
                    "light_commercial",
                    "heavy_commercial",
                ],
            },
            {
                "skill": "institutional_projects",
                "subskills": [
                    "hospitals",
                    "schools",
                    "universities",
                    "government_buildings",
                    "churches",
                    "sports_facilities",
                    "institutional",
                    "municipal",
                    "federal_projects",
                ],
            },
            {
                "skill": "industrial_projects",
                "subskills": [
                    "warehouses",
                    "manufacturing_facilities",
                    "data_centers",
                    "laboratories",
                    "industrial",
                    "chemical_plants",
                    "oil_refineries",
                    "nuclear_facilities",
                ],
            },
            {
                "skill": "infrastructure_projects",
                "subskills": [
                    "roads",
                    "bridges",
                    "tunnels",
                    "utilities",
                    "water_treatment",
                    "sewage_systems",
                    "power_plants",
                    "telecommunications",
                    "airports",
                    "railways",
                    "ports",
                    "dams",
                ],
            },
            {
                "skill": "specialty_construction",
                "subskills": [
                    "clean_rooms",
                    "food_processing",
                    "pharmaceutical",
                    "solar_farms",
                    "wind_farms",
                    "green_building",
                    "leed_certified",
                    "passive_house",
                    "modular_construction",
                    "prefab_construction",
                    "high_rise",
                    "underground_construction",
                    "marine_construction",
                    "mining_projects",
                ],
            },
            {
                "skill": "project_types",
                "subskills": [
                    "new_construction",
                    "renovation",
                    "remodeling",
                    "restoration",
                    "addition",
                    "tenant_improvement",
                    "retrofit",
                    "maintenance",
                    "emergency_repair",
                    "historic_preservation",
                ],
            },
            {
                "skill": "environmental_conditions",
                "subskills": [
                    "urban_construction",
                    "suburban_construction",
                    "rural_construction",
                    "coastal_projects",
                    "mountain_projects",
                    "desert_construction",
                    "cold_climate",
                    "hot_climate",
                    "seismic_zones",
                    "hurricane_zones",
                    "flood_zones",
                ],
            },
            {
                "skill": "project_delivery_methods",
                "subskills": [
                    "fast_track_projects",
                    "design_build",
                    "traditional_bid",
                    "cost_plus",
                    "fixed_price",
                    "emergency_projects",
                    "scheduled_maintenance",
                    "multi_phase_projects",
                    "long_term_projects",
                    "short_term_projects",
                ],
            },
        ],
        "certifications": [
            {
                "skill": "safety_certifications",
                "subskills": [
                    "osha_10",
                    "osha_30",
                    "osha_construction_focus_four",
                    "first_aid_cpr",
                    "fall_protection",
                    "confined_space",
                    "hazmat_awareness",
                    "hazmat_operations",
                    "respiratory_protection",
                    "hearing_conservation",
                    "lockout_tagout",
                    "crane_signal_person",
                    "rigging_certification",
                    "scaffold_competent_person",
                    "excavation_competent_person",
                ],
            },
            {
                "skill": "electrical_certifications",
                "subskills": [
                    "journeyman_electrician",
                    "master_electrician",
                    "electrical_inspector",
                    "low_voltage_license",
                    "fire_alarm_certification",
                ],
            },
            {
                "skill": "plumbing_certifications",
                "subskills": [
                    "journeyman_plumber",
                    "master_plumber",
                    "backflow_prevention",
                    "gas_line_certification",
                ],
            },
            {
                "skill": "hvac_certifications",
                "subskills": [
                    "hvac_epa_certification",
                    "refrigerant_handling",
                    "hvac_license",
                ],
            },
            {
                "skill": "welding_certifications",
                "subskills": [
                    "welding_aws_d1_1",
                    "welding_aws_d1_5",
                    "welding_6g_certification",
                    "pipe_welding_certification",
                    "structural_welding",
                    "aluminum_welding",
                    "stainless_welding",
                    "underwater_welding",
                ],
            },
            {
                "skill": "equipment_operator_certifications",
                "subskills": [
                    "forklift_license",
                    "crane_operator_cco",
                    "crane_operator_nccco",
                    "aerial_lift_certification",
                    "scissor_lift_certification",
                    "boom_lift_certification",
                    "heavy_equipment_operator",
                    "excavator_certification",
                    "bulldozer_certification",
                    "cdl_license",
                    "cdl_hazmat",
                ],
            },
            {
                "skill": "environmental_certifications",
                "subskills": [
                    "asbestos_supervisor",
                    "asbestos_worker",
                    "lead_renovation_rrp",
                    "lead_abatement",
                    "mold_remediation",
                ],
            },
            {
                "skill": "inspection_certifications",
                "subskills": [
                    "building_inspector",
                    "plans_examiner",
                    "accessibility_inspector",
                    "energy_auditor",
                    "home_inspector",
                    "code_official",
                    "quality_control_inspector",
                    "cqm_certification",
                ],
            },
            {
                "skill": "green_building_certifications",
                "subskills": [
                    "green_building_professional",
                    "leed_ap",
                    "leed_green_associate",
                    "passive_house_builder",
                ],
            },
            {
                "skill": "management_certifications",
                "subskills": [
                    "pmp_certification",
                    "construction_manager",
                    "project_management_construction",
                    "lean_construction",
                    "six_sigma",
                ],
            },
            {
                "skill": "technology_certifications",
                "subskills": [
                    "autocad_certified",
                    "revit_certified",
                    "bim_manager",
                    "drone_pilot_part_107",
                    "3d_scanning_certified",
                ],
            },
            {
                "skill": "industry_specific_certifications",
                "subskills": [
                    "nuclear_badge",
                    "twic_card",
                    "security_clearance",
                    "railroad_worker",
                    "maritime_certification",
                    "airport_badge",
                    "hospital_worker",
                    "food_safety_certification",
                ],
            },
        ],
        "safety_training": [
            {
                "skill": "basic_safety_training",
                "subskills": [
                    "construction_safety_orientation",
                    "site_specific_safety",
                    "hazard_recognition",
                    "accident_prevention",
                    "safety_meeting_participation",
                    "toolbox_talks",
                    "job_hazard_analysis",
                    "risk_assessment",
                    "incident_reporting",
                    "near_miss_reporting",
                    "emergency_procedures",
                    "evacuation_procedures",
                ],
            },
            {
                "skill": "ppe_training",
                "subskills": [
                    "ppe_training",
                    "hard_hat_safety",
                    "eye_protection",
                    "hearing_protection",
                    "respiratory_protection_fit_test",
                    "fall_protection_harness",
                    "cut_resistant_gloves",
                    "chemical_resistant_clothing",
                    "high_visibility_clothing",
                ],
            },
            {
                "skill": "fall_protection_training",
                "subskills": [
                    "fall_protection_basic",
                    "fall_protection_competent_person",
                    "ladder_safety",
                    "scaffold_safety",
                    "scaffold_erection",
                    "aerial_lift_safety",
                    "roof_safety",
                    "leading_edge_protection",
                    "safety_net_systems",
                    "guardrail_systems",
                ],
            },
            {
                "skill": "confined_space_training",
                "subskills": [
                    "confined_space_entry",
                    "confined_space_attendant",
                    "confined_space_supervisor",
                    "atmospheric_testing",
                    "ventilation_systems",
                    "rescue_procedures",
                ],
            },
            {
                "skill": "hazardous_materials_training",
                "subskills": [
                    "hazcom_training",
                    "chemical_safety",
                    "asbestos_awareness",
                    "asbestos_worker_training",
                    "lead_safety_awareness",
                    "lead_worker_training",
                    "silica_exposure_training",
                    "mold_awareness",
                    "bloodborne_pathogens",
                ],
            },
            {
                "skill": "electrical_safety_training",
                "subskills": [
                    "electrical_safety_basics",
                    "arc_flash_training",
                    "electrical_ppe",
                    "lockout_tagout_electrical",
                    "grounding_bonding",
                    "electrical_hazard_recognition",
                ],
            },
            {
                "skill": "equipment_safety_training",
                "subskills": [
                    "crane_safety",
                    "rigging_safety",
                    "forklift_safety",
                    "heavy_equipment_safety",
                    "power_tool_safety",
                    "hand_tool_safety",
                    "welding_safety",
                    "cutting_torch_safety",
                    "concrete_equipment_safety",
                ],
            },
            {
                "skill": "environmental_safety_training",
                "subskills": [
                    "heat_stress_prevention",
                    "cold_stress_prevention",
                    "noise_exposure_training",
                    "ergonomics_training",
                    "lifting_techniques",
                    "material_handling",
                    "housekeeping_safety",
                ],
            },
            {
                "skill": "fire_safety_training",
                "subskills": [
                    "fire_prevention",
                    "fire_extinguisher_training",
                    "hot_work_permits",
                    "flammable_materials",
                    "fire_watch_training",
                    "emergency_response",
                ],
            },
            {
                "skill": "specialized_safety_training",
                "subskills": [
                    "excavation_safety",
                    "trenching_safety",
                    "demolition_safety",
                    "roofing_safety",
                    "steel_erection_safety",
                    "concrete_safety",
                    "masonry_safety",
                    "painting_safety",
                ],
            },
            {
                "skill": "emergency_response_training",
                "subskills": [
                    "first_aid_basic",
                    "first_aid_wilderness",
                    "cpr_aed",
                    "emergency_response_team",
                    "spill_response",
                    "medical_emergency_response",
                    "fire_emergency_response",
                    "severe_weather_response",
                ],
            },
            {
                "skill": "industry_specific_safety",
                "subskills": [
                    "transportation_safety",
                    "highway_work_zone",
                    "nuclear_safety",
                    "petroleum_safety",
                    "marine_safety",
                    "aviation_safety",
                    "railroad_safety",
                    "mining_safety",
                ],
            },
        ],
    }

    # WE COULD ALSO SEARCH THEM DIRECTLY IN THE DB FOR COMPLETE GENERIC COVERAGE
    return json.dumps(skill_categories, indent=2, ensure_ascii=False)
